"""A canonical status set, and the SQL literals that spell it out again.

`LIVE_SESSION_STATUSES` names the session statuses meaning "this session is live". Eleven queries do
not use it — they write the six strings out inside their SQL. `_DISPATCH_TERMINAL_STATUSES` has five
such twins, and three more constants have one to three each: 22 files, 5 constants.

THIS REPO HAS ALREADY PAID FOR THIS EXACT BUG. From the frozen pre-split `control_agent` fixture:

    ALLOWLIST, never a blocklist (fixed 2026-07-26). This gate used to be
    `status NOT IN ('stopped','failed','ended','cancelled')`, which silently treats every status NOT
    on that list as LIVE. `lost` is not on it — so an agent whose worker was lost months ago read as
    "already running" forever ... Live-reproduced on the whole ef- team (four sessions stuck `lost`
    with ended_at 2026-04-30), which were permanently unstartable from the dashboard.

The fix at that site says: "Use the canonical live sets instead, so a new session status can never
silently mean 'live' here again." It was applied to ONE gate. Twenty-two other files still spell the
sets out, and nothing connects them to the constants they copy.

WHAT THIS GATE IS FOR, and it is not tidiness. Add a status to a canonical set and every hardcoded
twin silently keeps the old meaning — the same shape as the incident, in twenty-two places. So it
asserts the CONSTANT'S VALUE against the ledger: change the constant and this fails, naming every
file whose SQL must change with it. That is the failure the `lost` incident needed and did not have.

IT RULES NOTHING ELSE. Repointing twenty-two queries at their constants is a real refactor with real
risk — several are hot liveness queries — and which of them SHOULD share an owner is a reviewer's
call. Four differently-named constants hold identical values, so nine further literals cannot be
attributed to one owner at all and are deliberately out of scope. Freezing today's population stops
it growing while that stays open.
"""

from __future__ import annotations

import ast
import pathlib
import re
import unittest

REPO = pathlib.Path(__file__).resolve().parents[2]
PRUNE = {"node_modules", "fixtures", "__pycache__", ".git", ".venv", "tests"}

#: Constant -> where it is defined, what it holds, and which files spell it out in SQL instead.
#: Generated by scanning, not typed by hand. Shrinking a `hardcoded_in` list is the GOOD direction:
#: it means a query now uses the constant.
FROZEN: dict[str, dict] = {
    # PAID DOWN TO ZERO on 2026-08-29, and the ledger entry is worth keeping for what it got wrong.
    # These eleven modules were recorded here as hardcoding `LIVE_SESSION_STATUSES` -- the
    # `agent_sessions.status` live set. Not one of them was filtering `agent_sessions`. All eleven
    # filter `terminal_sessions.status`, and they matched this constant only because the two sets
    # have the same six members. Attributing them to the session constant is how a set-equality scan
    # reads a coincidence as an identity, which is the thing this file's sibling gate warns about.
    #
    # They now interpolate `TERMINAL_LIVE_FILTER_SQL` from `api_core/terminal_status.py` -- a set
    # that is deliberately NOT this one, and whose disputed member (`recovering`, absent from the
    # terminal vocabulary) is pinned open for a reviewer in
    # `test_the_live_terminal_filter_has_one_owner.py`.
    "LIVE_SESSION_STATUSES": {
        "owner": "service/api_core/tuning.py",
        "values": ["active", "attached", "idle", "recovering", "running", "starting"],
        "hardcoded_in": [],
    },
    # DECLARED 2026-08-18 when the value set got its FIRST NAME. `("pending", "claimed")` — a queued
    # instruction that has not been settled — was spelled out in eight SQL statements across three
    # modules and named nowhere, so this gate had nothing to attribute them to. Writing
    # `_UNSETTLED_CONTROL_STATUSES` in the new stuck-control reconciler made the set bindable, and the
    # gate demanded the declaration on the same run.
    #
    # ONE VOCABULARY, TWO TABLES. `dispatch_controls` and `terminal_controls` both use pending/claimed
    # for "queued, not yet settled". They are different tables and the queries below are not
    # interchangeable, but the STATUS WORDS are one vocabulary: adding a third unsettled state (say
    # `applying`) would have to reach every site here or each would silently keep the old meaning —
    # which is exactly the `lost` incident this file was written from, in eight more places.
    "_UNSETTLED_CONTROL_STATUSES": {
        "owner": "service/reconcilers/stuck_controls.py",
        "values": ["claimed", "pending"],
        "hardcoded_in": [
            "service/api_core/active_run_discard.py",
            "service/api_core/superseded_bridge_stops.py",
            "service/reconcilers/terminal_controls.py",
        ],
    },
    "_DISPATCH_TERMINAL_STATUSES": {
        "owner": "service/api_core/dispatch_state.py",
        "values": ["cancelled", "completed", "failed"],
        "hardcoded_in": [
            "service/api_core/dispatch_sweeps.py",
            "service/reconcilers/dispatch_lifecycle.py",
            "service/routers/contracts.py",
            "service/routers/dispatch_messages/handoff_repair.py",
            "service/routers/stats.py",
        ],
    },
    "_ENVIRONMENT_HEARTBEAT_STATUSES": {
        "owner": "service/env_status.py",
        "values": ["degraded", "online"],
        "hardcoded_in": [
            "service/reconcilers/terminal_controls.py",
        ],
    },
    "_LIVE_SESSION_STATUSES": {
        "owner": "service/api_core/liveness.py",
        "values": ["cli-takeover", "recovering", "restarting", "running", "starting"],
        "hardcoded_in": [
            "service/api_core/managed_env.py",
            "service/api_core/reconcilable_runs_query.py",
        ],
    },
    # ALSO PAID DOWN on 2026-08-29. These three were the honest half of the population: they spelled
    # out exactly the declared active set, with no disputed member. They now interpolate
    # `TERMINAL_ACTIVE_STATUS_SQL`, which renders THIS constant -- a different fragment from the one
    # the eleven above took, because the two groups mean different things and merging them would
    # have changed what four filters consider a live terminal.
    "_TERMINAL_ACTIVE_STATUSES": {
        "owner": "service/api_core/terminal_status.py",
        "values": ["active", "attached", "idle", "running", "starting"],
        "hardcoded_in": [],
    },
}

IN_LIST = re.compile(r"\bIN\s*\(\s*((?:'[^']*'\s*,\s*)+'[^']*')\s*\)", re.IGNORECASE)


def _sources() -> list[tuple[str, str]]:
    out = []
    for path in sorted((REPO / "service").rglob("*.py")):
        rel = path.relative_to(REPO)
        if PRUNE & set(rel.parts):
            continue
        out.append((rel.as_posix(), path.read_text(encoding="utf-8")))
    return out


def _named_sets(sources) -> dict[str, tuple[frozenset, str]]:
    """Module-level assignments of a small set/list/tuple of plain strings."""
    found: dict[str, tuple[frozenset, str]] = {}
    for rel, src in sources:
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue
        for node in tree.body:
            if not isinstance(node, ast.Assign) or len(node.targets) != 1:
                continue
            target = node.targets[0]
            if not isinstance(target, ast.Name):
                continue
            value = node.value
            if isinstance(value, ast.Call) and getattr(value.func, "id", "") == "frozenset" and value.args:
                value = value.args[0]
            if not isinstance(value, (ast.Set, ast.List, ast.Tuple)):
                continue
            items = []
            for elt in value.elts:
                if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                    items.append(elt.value)
                else:
                    break
            else:
                if 2 <= len(items) <= 12:
                    found[target.id] = (frozenset(items), rel)
    return found


def _literal_twins(sources, named) -> dict[str, set]:
    """Files whose SQL spells out a set exactly matching exactly ONE named constant."""
    by_values: dict[frozenset, list] = {}
    for name, (values, _owner) in named.items():
        by_values.setdefault(values, []).append(name)
    twins: dict[str, set] = {}
    for rel, src in sources:
        for match in IN_LIST.finditer(src):
            values = frozenset(v.strip().strip("'") for v in match.group(1).split(","))
            owners = by_values.get(values)
            if not owners or len(owners) != 1:
                continue  # ambiguous ownership is out of scope; see the module docstring
            twins.setdefault(owners[0], set()).add(rel)
    return twins


class StatusSetLiteralTwinsTests(unittest.TestCase):
    def test_each_constant_still_holds_the_values_its_twins_assume(self):
        """THE ONE THAT MATTERS. Change a canonical set and the hardcoded copies keep the OLD
        meaning, silently, in every file listed. This turns that into a failure that names them."""
        named = _named_sets(_sources())
        for name, entry in FROZEN.items():
            with self.subTest(constant=name):
                self.assertIn(name, named, f"{name} is gone; the SQL twins below now copy nothing")
                values, owner = named[name]
                self.assertEqual(owner, entry["owner"], f"{name} moved; update the ledger")
                self.assertEqual(
                    sorted(values), entry["values"],
                    f"{name} changed. Every one of these files spells the OLD values out in SQL and "
                    f"will keep the old meaning until updated with it: {entry['hardcoded_in']}",
                )

    def test_no_new_file_starts_spelling_a_constant_out(self):
        sources = _sources()
        actual = _literal_twins(sources, _named_sets(sources))
        for name, entry in FROZEN.items():
            with self.subTest(constant=name):
                self.assertEqual(
                    sorted(actual.get(name, set())), entry["hardcoded_in"],
                    f"the files hardcoding {name} changed. FEWER is good -- a query now uses the "
                    f"constant, so shrink this list. MORE means a new copy that will not move when "
                    f"the constant does.",
                )

    def test_the_scanner_is_not_silently_matching_nothing(self):
        """POSITIVE CONTROL, and it had to learn what SUCCESS looks like.

        It used to require every FROZEN constant to still have twins, which made a fully paid-down
        entry indistinguishable from a broken scanner -- and `test_no_new_file_starts_spelling_a_
        constant_out` invites exactly that payment ("FEWER is good"). On 2026-08-29 two entries went
        to zero in one change (11 sites and 3 sites), and this test failed for the success.

        So the claim is narrower and still real: every constant that CLAIMS twins must have them,
        and the scanner must still be finding a population rather than nothing.
        """
        sources = _sources()
        named = _named_sets(sources)
        self.assertGreater(len(named), 10, "the named-set scan found almost nothing")
        twins = _literal_twins(sources, named)
        claiming = sorted(name for name, entry in FROZEN.items() if entry["hardcoded_in"])
        self.assertEqual(sorted(twins), claiming, "the constant list itself drifted")
        #: MEASURED after the 2026-08-29 payment: 11 twin sites across four constants, down from 25.
        #: A floor, not a target -- it goes DOWN when a set is paid off, and lowering it is part of
        #: making that payment rather than a separate decision.
        self.assertGreaterEqual(sum(len(v) for v in twins.values()), 11)

    def test_the_twin_detector_fires_on_a_fixture(self):
        fixture = [("service/fake.py", "Q = \"SELECT 1 WHERE s IN ('a','b')\"\n")]
        named = {"FAKE_SET": (frozenset({"a", "b"}), "service/fake.py")}
        self.assertEqual(_literal_twins(fixture, named), {"FAKE_SET": {"service/fake.py"}})
        self.assertEqual(
            _literal_twins([("x.py", "s IN ('a','c')")], named), {},
            "a different value set must not be attributed to that constant",
        )
